# Generated by Django 5.0.2 on 2024-05-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0009_answers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
