# Generated by Django 5.0.2 on 2024-05-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_answers_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='querry',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
