# Generated by Django 5.0.2 on 2024-09-25 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0012_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
